[package]
name = "core_lib"
version = "0.1.0"
authors = ["Peter Mezei"]
edition = "2018"

[dependencies]
serde = "*"
serde_derive = "*"
serde_yaml = "*"
chrono = { version = "*", features = ["serde"] }
dirs = "*"